name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: rockylinux/8/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: melihsavdert/docker-rockylinux-systemd:8
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: rockylinux/9/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: melihsavdert/docker-rockylinux-systemd:latest,melihsavdert/docker-rockylinux-systemd:9
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ubuntu/20.04/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: melihsavdert/docker-ubuntu-systemd:20.04,melihsavdert/docker-ubuntu-systemd:20.04-focal
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ubuntu/22.04/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: melihsavdert/docker-ubuntu-systemd:latest,melihsavdert/docker-ubuntu-systemd:22.04,melihsavdert/docker-ubuntu-systemd:22.04-jammy
